### ISSUE TITLE
Create 'teaser' view as requested

### ISSUE THREAD

**Issue by fribibb** [fribibb/DTOstrap#16]
Likely similar to the .media style.
@paulkilla to provide screenshot of example

**Comment by paulkilla** [comment]
![screen shot 2017-04-03 at 2 46 53 pm](https://cloud.githubusercontent.com/assets/6803470/24595697/76615302-187c-11e7-846c-c52be7ec0d33.png)

**Comment by fribibb** [comment]
Achievable through using .list-group around .media
